# Generated by Django 4.1.1 on 2022-10-19 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('dreams', models.TextField(blank=True, max_length=9999, null=True)),
                ('meals', models.TextField(blank=True, max_length=9999, null=True)),
                ('conversations', models.TextField(blank=True, max_length=9999, null=True)),
                ('sex', models.TextField(blank=True, max_length=9999, null=True)),
                ('ssilo4ka_progress', models.TextField(blank=True, max_length=9999, null=True)),
                ('went_well', models.TextField(blank=True, max_length=9999, null=True)),
                ('could_be_better', models.TextField(blank=True, max_length=9999, null=True)),
                ('ultimate_questions', models.TextField(blank=True, max_length=9999, null=True)),
                ('wake_up_time', models.TimeField()),
                ('bed_time', models.TimeField()),
                ('woke_up', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
